import type { Course, Job, ResumePackage } from "./types";

export const courses: Course[] = [
  {
    id: "java-fundamentals",
    slug: "java-fundamentals",
    title: "Java Fundamentals to Advanced",
    category: "Programming",
    description: "Master OOP, collections, streams, multithreading, and modern Java features.",
    longDescription:
      "A comprehensive Java course covering core concepts, object-oriented programming, exception handling, collections framework, Java 8+ features including streams and lambdas, multithreading, and best practices used in enterprise applications.",
    price: 4999,
    duration: "40 hours",
    level: "Beginner",
    rating: 4.8,
    students: 2840,
    modules: [
      "Java Basics & OOP",
      "Collections & Generics",
      "Exception Handling",
      "Streams & Lambdas",
      "Multithreading",
      "File I/O & Serialization",
      "Design Patterns",
      "Project: REST API Backend",
    ],
    icon: "☕",
    color: "from-orange-500 to-red-600",
  },
  {
    id: "sql-mastery",
    slug: "sql-mastery",
    title: "SQL & Database Design",
    category: "Database",
    description: "Learn queries, joins, indexing, stored procedures, and database optimization.",
    longDescription:
      "From SELECT statements to advanced query optimization, this course teaches relational database design, normalization, complex joins, window functions, indexing strategies, and performance tuning for real-world applications.",
    price: 3499,
    duration: "25 hours",
    level: "Beginner",
    rating: 4.7,
    students: 1920,
    modules: [
      "SQL Fundamentals",
      "Joins & Subqueries",
      "Aggregations & Window Functions",
      "Database Design & Normalization",
      "Indexing & Performance",
      "Stored Procedures",
      "Transactions & ACID",
      "Project: E-commerce DB",
    ],
    icon: "🗄️",
    color: "from-blue-500 to-cyan-600",
  },
  {
    id: "mongodb-nosql",
    slug: "mongodb-nosql",
    title: "MongoDB & NoSQL",
    category: "Database",
    description: "Document databases, aggregation pipelines, indexing, and Atlas cloud deployment.",
    longDescription:
      "Dive into MongoDB with CRUD operations, schema design patterns, aggregation framework, indexing strategies, replication, sharding, and deploying applications with MongoDB Atlas on the cloud.",
    price: 3999,
    duration: "20 hours",
    level: "Intermediate",
    rating: 4.6,
    students: 1450,
    modules: [
      "NoSQL Concepts",
      "CRUD Operations",
      "Schema Design Patterns",
      "Aggregation Pipeline",
      "Indexing & Performance",
      "Replication & Sharding",
      "MongoDB Atlas",
      "Project: Blog API",
    ],
    icon: "🍃",
    color: "from-green-500 to-emerald-600",
  },
  {
    id: "spring-boot",
    slug: "spring-boot",
    title: "Spring Boot Masterclass",
    category: "Framework",
    description: "Build production-ready REST APIs with Spring Boot, Security, and JPA.",
    longDescription:
      "Learn to build enterprise Java applications with Spring Boot including REST APIs, Spring Data JPA, Spring Security, validation, exception handling, testing, and deployment strategies.",
    price: 5999,
    duration: "35 hours",
    level: "Intermediate",
    rating: 4.9,
    students: 2100,
    modules: [
      "Spring Core & DI",
      "Spring Boot Basics",
      "REST API Development",
      "Spring Data JPA",
      "Spring Security",
      "Validation & Exception Handling",
      "Testing with JUnit",
      "Project: Full Stack API",
    ],
    icon: "🌱",
    color: "from-lime-500 to-green-600",
  },
  {
    id: "microservices",
    slug: "microservices",
    title: "Microservices Architecture",
    category: "Architecture",
    description: "Design scalable systems with Docker, Kubernetes, API Gateway, and messaging.",
    longDescription:
      "Master microservices architecture patterns including service decomposition, inter-service communication, API gateways, circuit breakers, event-driven architecture, Docker containerization, and Kubernetes orchestration.",
    price: 6999,
    duration: "30 hours",
    level: "Advanced",
    rating: 4.8,
    students: 1680,
    modules: [
      "Microservices Fundamentals",
      "Service Communication",
      "API Gateway Pattern",
      "Circuit Breaker & Resilience",
      "Event-Driven Architecture",
      "Docker Containerization",
      "Kubernetes Basics",
      "Project: E-commerce Microservices",
    ],
    icon: "🔧",
    color: "from-purple-500 to-violet-600",
  },
  {
    id: "aws-cloud",
    slug: "aws-cloud",
    title: "AWS Cloud Practitioner",
    category: "Cloud",
    description: "EC2, S3, Lambda, RDS, IAM, and cloud architecture best practices.",
    longDescription:
      "Get hands-on with Amazon Web Services covering compute, storage, databases, networking, security, serverless computing, and preparing for the AWS Cloud Practitioner certification.",
    price: 5499,
    duration: "28 hours",
    level: "Beginner",
    rating: 4.7,
    students: 2350,
    modules: [
      "Cloud Computing Basics",
      "EC2 & Auto Scaling",
      "S3 & Storage Services",
      "RDS & DynamoDB",
      "Lambda & Serverless",
      "IAM & Security",
      "VPC & Networking",
      "Certification Prep",
    ],
    icon: "☁️",
    color: "from-amber-500 to-orange-600",
  },
  {
    id: "cloud-devops",
    slug: "cloud-devops",
    title: "Cloud & DevOps Engineering",
    category: "Cloud",
    description: "CI/CD pipelines, Terraform, monitoring, and multi-cloud deployment strategies.",
    longDescription:
      "Learn DevOps practices including CI/CD with GitHub Actions and Jenkins, Infrastructure as Code with Terraform, container orchestration, monitoring with Prometheus/Grafana, and deploying across AWS, Azure, and GCP.",
    price: 7499,
    duration: "32 hours",
    level: "Advanced",
    rating: 4.9,
    students: 1320,
    modules: [
      "DevOps Culture & Practices",
      "CI/CD Pipelines",
      "Docker & Kubernetes",
      "Terraform & IaC",
      "Monitoring & Logging",
      "Multi-Cloud Strategy",
      "Security & Compliance",
      "Project: Full DevOps Pipeline",
    ],
    icon: "🚀",
    color: "from-indigo-500 to-blue-600",
  },
];

export const resumePackages: ResumePackage[] = [
  {
    id: "resume-basic",
    name: "Basic Resume",
    description: "ATS-friendly resume crafted for freshers and career switchers.",
    price: 999,
    features: [
      "1-page ATS-optimized resume",
      "Keyword optimization",
      "1 round of revisions",
      "Delivery in 3 business days",
    ],
    formats: ["PDF", "Word"],
    deliveryDays: 3,
  },
  {
    id: "resume-professional",
    name: "Professional Resume",
    description: "Polished resume with cover letter for mid-level professionals.",
    price: 1999,
    features: [
      "2-page professional resume",
      "Custom cover letter",
      "LinkedIn profile optimization tips",
      "2 rounds of revisions",
      "Delivery in 2 business days",
    ],
    formats: ["PDF", "Word"],
    deliveryDays: 2,
    popular: true,
  },
  {
    id: "resume-executive",
    name: "Executive Package",
    description: "Premium resume suite for senior roles and leadership positions.",
    price: 3499,
    features: [
      "Executive resume + cover letter",
      "LinkedIn headline & summary rewrite",
      "Portfolio/project descriptions",
      "Unlimited revisions for 7 days",
      "1-on-1 consultation call (30 min)",
      "Delivery in 1 business day",
    ],
    formats: ["PDF", "Word"],
    deliveryDays: 1,
  },
];

export const jobs: Job[] = [
  {
    id: "job-1",
    title: "Java Developer",
    company: "Infosys",
    location: "Bangalore, India",
    type: "Full-time",
    experience: "2-4 years",
    salary: "₹8-12 LPA",
    skills: ["Java", "Spring Boot", "SQL", "REST APIs"],
    postedAt: "2026-06-14",
    applyUrl: "#",
  },
  {
    id: "job-2",
    title: "Full Stack Engineer",
    company: "TCS",
    location: "Hyderabad, India",
    type: "Full-time",
    experience: "3-5 years",
    salary: "₹10-15 LPA",
    skills: ["React", "Node.js", "MongoDB", "AWS"],
    postedAt: "2026-06-13",
    applyUrl: "#",
  },
  {
    id: "job-3",
    title: "Cloud DevOps Engineer",
    company: "Wipro",
    location: "Pune, India",
    type: "Full-time",
    experience: "4-6 years",
    salary: "₹12-18 LPA",
    skills: ["AWS", "Docker", "Kubernetes", "Terraform"],
    postedAt: "2026-06-12",
    applyUrl: "#",
  },
  {
    id: "job-4",
    title: "Microservices Architect",
    company: "Accenture",
    location: "Remote",
    type: "Remote",
    experience: "8+ years",
    salary: "₹25-35 LPA",
    skills: ["Java", "Microservices", "Kafka", "Spring Cloud"],
    postedAt: "2026-06-11",
    applyUrl: "#",
  },
  {
    id: "job-5",
    title: "SQL Database Administrator",
    company: "Capgemini",
    location: "Chennai, India",
    type: "Full-time",
    experience: "3-5 years",
    salary: "₹7-11 LPA",
    skills: ["SQL Server", "PostgreSQL", "Performance Tuning"],
    postedAt: "2026-06-10",
    applyUrl: "#",
  },
  {
    id: "job-6",
    title: "AWS Solutions Architect",
    company: "HCL Technologies",
    location: "Noida, India",
    type: "Full-time",
    experience: "5-8 years",
    salary: "₹18-28 LPA",
    skills: ["AWS", "Cloud Architecture", "Terraform", "Security"],
    postedAt: "2026-06-09",
    applyUrl: "#",
  },
  {
    id: "job-7",
    title: "Junior Java Developer",
    company: "Cognizant",
    location: "Kolkata, India",
    type: "Full-time",
    experience: "0-2 years",
    salary: "₹4-6 LPA",
    skills: ["Java", "OOP", "SQL", "Git"],
    postedAt: "2026-06-08",
    applyUrl: "#",
  },
  {
    id: "job-8",
    title: "MongoDB Developer",
    company: "Tech Mahindra",
    location: "Mumbai, India",
    type: "Contract",
    experience: "2-4 years",
    salary: "₹9-13 LPA",
    skills: ["MongoDB", "Node.js", "Aggregation", "Atlas"],
    postedAt: "2026-06-07",
    applyUrl: "#",
  },
];

export function formatPrice(amount: number): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(amount);
}

export function getCourseBySlug(slug: string): Course | undefined {
  return courses.find((course) => course.slug === slug);
}

export function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString("en-IN", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}
